security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: https://idpdecathlon.oxylane.com/ext/JWKS
        issuer: idpdecathlon.org
        userinfo-endpoint: https://idpdecathlon.oxylane.com/idp/userinfo.openid
